### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by aehrmann** [moxley/atom-ruby-test#44] opened 2015-02-20 21:19 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.182.0
**System**: Mac OS X 10.10.2
**Thrown From**: [ruby-test](https://github.com/moxley/atom-ruby-test) package, v0.9.5

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /Users/aehrmann/.atom/packages/ruby-test/lib/test-runner.coffee:32

TypeError: Cannot read property 'replace' of undefined
  at TestRunner.module.exports.TestRunner.command (/Users/aehrmann/.atom/packages/ruby-test/lib/test-runner.coffee:32:10)
  at TestRunner.command (/Users/aehrmann/.atom/packages/ruby-test/lib/test-runner.coffee:1:1)
  at TestRunner.module.exports.TestRunner.run (/Users/aehrmann/.atom/packages/ruby-test/lib/test-runner.coffee:15:28)
  at RubyTestView.module.exports.RubyTestView.runTest (/Users/aehrmann/.atom/packages/ruby-test/lib/ruby-test-view.coffee:66:13)
  at RubyTestView.module.exports.RubyTestView.testAll (/Users/aehrmann/.atom/packages/ruby-test/lib/ruby-test-view.coffee:53:6)
  at atom-workspace.<anonymous> (/Users/aehrmann/.atom/packages/ruby-test/lib/ruby-test-view.coffee:25:67)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:176:20)

```

### Commands

```
     -3:57.4 core:move-down (atom-text-editor.editor.mini)
     -3:57.2 core:confirm (atom-text-editor.editor.mini)
     -3:57.2 rspec:run-all (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-one-dark-ui)
     -3:14.8 settings-view:open (atom-pane.pane.active)
     -3:09.2 core:confirm (atom-text-editor.editor.mini)
     -3:06.8 editor:delete-to-beginning-of-word (atom-text-editor.editor.mini)
     -3:05.0 core:confirm (atom-text-editor.editor.mini)
     -2:58.6 core:backspace (atom-text-editor#ruby-test.rspecAllCommand.editor.mini)
     -2:47.5 core:close (div.settings-view.pane-item)
     -2:45.9 emmet:evaluate-math-expression (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-one-dark-ui)
     -2:42.7 core:close (atom-pane.pane.active)
     -2:36.1 ruby-test:test-all (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:41.0 settings-view:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-one-dark-ui)
     -0:35.4 core:confirm (atom-text-editor.editor.mini)
     -0:02.2 pane:show-previous-item (div.settings-view.pane-item)
     -0:00.9 ruby-test:test-all (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "language-objective-c",
      "archive-view",
      "autosave",
      "whitespace",
      "rspec"
    ]
  },
  "ruby-test": {
    "rspecAllCommand": "rspec",
    "shell": "zsh"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.3
autocomplete-plus, v2.1.6
color-picker, v1.4.4
emmet, v2.3.3
git-plus, v4.4.8
highlight-line, v0.9.3
monokai, v0.12.0
ruby-test, v0.9.5

# Dev
No dev packages
```

**Comment by andypearson** [comment] 2015-02-23 18:59
This seems to happen when trying to run "Ruby Test: Test All" when no files are open.

**Comment by andypearson** [comment] 2015-02-24 09:35
This also happens when the opened file is not a "runnable" test file, but it feels like "Ruby Test: Test All" should work when the editor is in any state.

I guess there would need to be a setting or a clever way of working out what to do when a usable file isn't open but a shortcut is used.

Can this issue be re-opened and I'll try and take a look at it?

**Comment by ozeron** [comment] 2015-03-03 17:00
When this error happens, second pane appears and I can't close it. Is there is any way to close this pane?
![pdf_renderer_rb_-__users_rubydev_documents_cropio_-_atom](https://cloud.githubusercontent.com/assets/3617121/6467519/6dd9904e-c1d7-11e4-9d6b-9dec8d7a81ec.jpg)

[Enter steps to reproduce below:]

1. Tried run `cmd-ctrl-y` on ordinal ruby file



**Atom Version**: 0.182.0
**System**: Mac OS X 10.10.2
**Thrown From**: [ruby-test](https://github.com/moxley/atom-ruby-test) package, v0.9.5

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /Users/rubydev/.atom/packages/ruby-test/lib/test-runner.coffee:32

TypeError: Cannot read property 'replace' of undefined
  at TestRunner.module.exports.TestRunner.command (/Users/rubydev/.atom/packages/ruby-test/lib/test-runner.coffee:32:10)
  at TestRunner.command (/Users/rubydev/.atom/packages/ruby-test/lib/test-runner.coffee:1:1)
  at TestRunner.module.exports.TestRunner.run (/Users/rubydev/.atom/packages/ruby-test/lib/test-runner.coffee:15:28)
  at RubyTestView.module.exports.RubyTestView.runTest (/Users/rubydev/.atom/packages/ruby-test/lib/ruby-test-view.coffee:66:13)
  at RubyTestView.module.exports.RubyTestView.testAll (/Users/rubydev/.atom/packages/ruby-test/lib/ruby-test-view.coffee:53:6)
  at atom-workspace.<anonymous> (/Users/rubydev/.atom/packages/ruby-test/lib/ruby-test-view.coffee:25:67)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:176:20)

```

### Commands

```
     -3:05.2 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
     -1:51.1 project-manager:toggle (atom-text-editor.editor)
     -1:49.4 core:confirm (atom-text-editor.editor.mini)
     -1:33.8 ruby-quick-test:run-tests (atom-text-editor.editor)
     -1:27.7 find-and-replace:select-next (atom-text-editor.editor)
  2x -1:23.3 core:save (atom-text-editor.editor)
     -0:19.1 linter:next-message (atom-text-editor.editor.is-focused)
     -0:04.5 ruby-test:test-all (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "disabledPackages": [
      "vim-mode"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.3
atom-color-highlight, v3.0.8
autocomplete-plus, v2.2.0
autocomplete-plus-async, v0.22.0
ember-snippets, v1.0.0
emmet, v2.3.4
git-projects, v1.8.1
highlight-line, v0.10.1
line-ending-converter, v1.0.0
linter, v0.12.0
linter-rubocop, v0.2.2
linter-ruby, v0.1.4
project-manager, v1.15.5
revert-buffer, v0.5.0
ruby-block, v0.2.2
ruby-block-converter, v3.2.0
ruby-define-method, v0.2.0
ruby-quick-test, v0.3.0
ruby-slim, v0.2.0
ruby-test, v0.9.5
script, v2.18.0

# Dev
No dev packages
```

**Closed** 2015-04-06 13:49 UTC

**Comment by tjstankus** [comment] 2015-09-05 17:17
I also see this issue running a test file for minitest.

The stacktrace:
```
TypeError: Cannot read property 'replace' of undefined
  at TestRunner.module.exports.TestRunner.command (/Users/tjs/Dropbox (Personal)/Atom/packages/ruby-test/lib/test-runner.coffee:32:10)
  at TestRunner.command (/Users/tjs/Dropbox (Personal)/Atom/packages/ruby-test/lib/test-runner.coffee:1:1)
  at TestRunner.module.exports.TestRunner.run (/Users/tjs/Dropbox (Personal)/Atom/packages/ruby-test/lib/test-runner.coffee:15:28)
  at RubyTestView.module.exports.RubyTestView.runTest (/Users/tjs/Dropbox (Personal)/Atom/packages/ruby-test/lib/ruby-test-view.coffee:72:13)
  at RubyTestView.module.exports.RubyTestView.testFile (/Users/tjs/Dropbox (Personal)/Atom/packages/ruby-test/lib/ruby-test-view.coffee:53:6)
  at atom-workspace.<anonymous> (/Users/tjs/Dropbox (Personal)/Atom/packages/ruby-test/lib/ruby-test-view.coffee:24:68)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)
```

One point of interest is that the test and code under test are in the same file. The test runs fine from the command line with `ruby <filename>`. I tried both with and without changing "Minitest command: run test file" to be the same as what I used on the command line.

Let me know if there's any other information you need to debug.

**Comment by moxley** [comment] 2015-09-22 15:38
@tjstankus: I'm not able to reproduce it:

<a href="http://www.youtube.com/watch?feature=player_embedded&v=_4se8iVmzh0
" target="_blank"><img src="http://img.youtube.com/vi/_4se8iVmzh0/0.jpg" alt="Atom ruby-test minitest" width="240" height="180" border="10" /></a>

Here's the test file from the video:
https://github.com/moxley/atom-ruby-test-samples/blob/master/minitest_sample/test/square_test.rb

**Comment by tothzit** [comment] 2016-03-31 16:48
I get the same error with no matter what .rb file I'm trying to run, including the minitest linked in the previous post or a simple 1+1. (They run fine from the Terminal.) Running OSX & Atom latest.

Uncaught TypeError: Cannot read property 'replace' of undefined
/Users/zita/.atom/packages/ruby-test/lib/test-runner.coffee:32
TypeError: Cannot read property 'replace' of undefined
    at TestRunner.module.exports.TestRunner.command (/Users/zita/.atom/packages/ruby-test/lib/test-runner.coffee:32:10)
    at TestRunner.command (/Users/zita/.atom/packages/ruby-test/lib/test-runner.coffee:1:1)
    at TestRunner.module.exports.TestRunner.run (/Users/zita/.atom/packages/ruby-test/lib/test-runner.coffee:15:28)
    at RubyTestView.module.exports.RubyTestView.runTest (/Users/zita/.atom/packages/ruby-test/lib/ruby-test-view.coffee:72:13)
    at RubyTestView.module.exports.RubyTestView.testSingle (/Users/zita/.atom/packages/ruby-test/lib/ruby-test-view.coffee:56:6)
    at atom-workspace.<anonymous> (/Users/zita/.atom/packages/ruby-test/lib/ruby-test-view.coffee:25:70)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)

**Comment by Tegalex** [comment] 2016-08-02 10:53
Hello,

I get same problem, this is stacktrace:

> TypeError: Cannot read property 'replace' of undefined
    at TestRunner.module.exports.TestRunner.command (file:///C:/Users/tegagni/.atom/packages/ruby-test/lib/test-runner.coffee:32:10)
    at TestRunner.command (file:///C:/Users/tegagni/.atom/packages/ruby-test/lib/test-runner.coffee:1:1)
    at TestRunner.module.exports.TestRunner.run (file:///C:/Users/tegagni/.atom/packages/ruby-test/lib/test-runner.coffee:15:28)
    at RubyTestView.module.exports.RubyTestView.runTest (file:///C:/Users/tegagni/.atom/packages/ruby-test/lib/ruby-test-view.coffee:72:13)
    at RubyTestView.module.exports.RubyTestView.testFile (file:///C:/Users/tegagni/.atom/packages/ruby-test/lib/ruby-test-view.coffee:53:6)
    at atom-workspace.<anonymous> (file:///C:/Users/tegagni/.atom/packages/ruby-test/lib/ruby-test-view.coffee:24:68)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\tegagni\AppData\Local\atom\app-1.9.0\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\tegagni\AppData\Local\atom\app-1.9.0\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\tegagni\AppData\Local\atom\app-1.9.0\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\tegagni\AppData\Local\atom\app-1.9.0\resources\app.asar\src\atom-environment.js:1104:28)
    at EventEmitter.outerCallback (C:\Users\tegagni\AppData\Local\atom\app-1.9.0\resources\app.asar\src\application-delegate.js:327:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)

Running with win7 64bit

**Comment by aert** [comment] 2017-06-25 19:15
Same issue here with Minitest, and "Test File":

```
/home/ari/.atom/packages/ruby-test/lib/test-runner.coffee:57
Hide Stack Trace
TypeError: Cannot read property 'replace' of undefined
    at TestRunner.module.exports.TestRunner.command (/home/ari/.atom/packages/ruby-test/lib/test-runner.coffee:57:10)
    at TestRunner.command (/home/ari/.atom/packages/ruby-test/lib/test-runner.coffee:1:1)
    at TestRunner.module.exports.TestRunner.run (/home/ari/.atom/packages/ruby-test/lib/test-runner.coffee:27:23)
    at RubyTestView.module.exports.RubyTestView.runTest (/home/ari/.atom/packages/ruby-test/lib/ruby-test-view.coffee:57:13)
    at RubyTestView.module.exports.RubyTestView.testFile (/home/ari/.atom/packages/ruby-test/lib/ruby-test-view.coffee:41:6)
    at atom-workspace.<anonymous> (/home/ari/.atom/packages/ruby-test/lib/ruby-test-view.coffee:16:68)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:265:35)
    at /opt/atom/resources/app/src/command-registry.js:3:65
    at Object.didConfirmSelection (/opt/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:106:35)
    at SelectListView.confirmSelection (/opt/atom/resources/app/node_modules/atom-select-list/src/select-list-view.js:313:26)
    at HTMLDivElement.core:confirm (/opt/atom/resources/app/node_modules/atom-select-list/src/select-list-view.js:81:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:265:35)
    at /opt/atom/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/atom/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app/src/window-event-handler.js:3:65)
The error was thrown from the ruby-test package. This issue has already been 
```

**Comment by gee-forr** [comment] 2017-06-29 12:06
Yep - looks like this error has resurfaced

**Comment by nolanpro** [comment] 2017-08-06 21:25
@gee-forr is the file you are attempting to run named *_test.rb or *_spec.rb? I realize it needs better error handling and could figure out if its a test file other ways, but the way it currently is, the filename needs to end in _test.rb or _spec.rb

**Comment by gee-forr** [comment] 2017-08-07 06:49
@nolanpro - So, I don't have this issue anymore... I can't say if the issue has been resolved or if it's still around, as I am experiencing another issue #109 instead.

But, to answer your question, all my tests are suffixed with `_spec.rb`.

**Comment by NawaafAlmansour** [comment] 2019-07-12 19:09
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.5
**Thrown From**: [ruby-test](https://github.com/moxley/atom-ruby-test) package 1.0.2


### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /Users/nawaf/.atom/packages/ruby-test/lib/test-runner.coffee:57

TypeError: Cannot read property 'replace' of undefined
    at TestRunner.module.exports.TestRunner.command (/packages/ruby-test/lib/test-runner.coffee:57:11)
    at TestRunner.command (/packages/ruby-test/lib/test-runner.coffee:1:1)
    at TestRunner.module.exports.TestRunner.run (/packages/ruby-test/lib/test-runner.coffee:27:23)
    at RubyTestView.module.exports.RubyTestView.runTest (/packages/ruby-test/lib/ruby-test-view.coffee:57:13)
    at RubyTestView.module.exports.RubyTestView.testFile (/packages/ruby-test/lib/ruby-test-view.coffee:41:6)
    at /packages/ruby-test/lib/ruby-test-view.coffee:16:68)
    at CommandRegistry.handleCommandEvent (/private/var/folders/_y/gv_cfxy13175jx2gjb1bh56c0000gn/T/AppTranslocation/7842AA57-854F-4833-98C3-CF13B8F517DF/d/Atom.app/Contents/Resources/app/static/<embedded>:11:348418)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (/private/var/folders/_y/gv_cfxy13175jx2gjb1bh56c0000gn/T/AppTranslocation/7842AA57-854F-4833-98C3-CF13B8F517DF/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1247210)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/private/var/folders/_y/gv_cfxy13175jx2gjb1bh56c0000gn/T/AppTranslocation/7842AA57-854F-4833-98C3-CF13B8F517DF/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1243344)
    at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/_y/gv_cfxy13175jx2gjb1bh56c0000gn/T/AppTranslocation/7842AA57-854F-4833-98C3-CF13B8F517DF/d/Atom.app/Contents/Resources/app/static/<embedded>:11:283624)
```

### Commands

```
  2x -5:44.7.0 core:backspace (input.hidden-input)
     -4:48.1.0 editor:newline (input.hidden-input)
     -4:44.9.0 autocomplete-plus:confirm (input.hidden-input)
     -4:44.8.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
  7x -4:37.4.0 core:backspace (input.hidden-input)
     -2:02.8.0 core:undo (div.line-number.cursor-line)
     -1:55.7.0 core:redo (div.line-number)
     -1:42.9.0 atom-psql:run_selection (div.line-number)
     -1:34.1.0 ruby-test:test-file (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-beautify 0.33.4 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-psql 0.33.0 
autoclose-html 0.23.0 
autocomplete-python 1.14.1 
autocomplete-ruby 0.2.8 
busy-signal 2.0.1 
color-indent 1.0.2 
color-picker 2.3.0 
emmet 2.4.3 
file-icons 2.1.33 
git-plus 8.7.1 
highlight-selected 0.16.0 
intentions 1.1.5 
kite 0.165.0 
language-pgsql 0.2.3 
linter 2.3.0 
linter-flake8 2.4.0 
linter-ruby 1.3.1 
linter-ui-default 1.7.1 
open-recent 5.0.0 
pigments 0.40.2 
platformio-ide-terminal 2.9.1 
python-autopep8 0.1.3 
ruby-test 1.0.2 
tool-bar 1.1.11 
vk-terminal 3.0.1 
```
