### ISSUE TITLE
click on filename in output pane should open it

### ISSUE THREAD

**Issue by gucki** [moxley/atom-ruby-test#65] opened 2015-07-23 08:34 UTC
Related to https://github.com/moxley/atom-ruby-test/issues/6

When clicking on a filename, ex. `test.rb:52`, in the output pane, that file should be opened and the cursor moved to that line.

**Comment by dancinglightning** [comment] 2015-07-25 11:18
So i'm too late, i was just going to suggest this. btw may be a double #7

I tried the package, which is a neat idea.

But this was one of the reasons i won't use it, the other being that in case the test pass, the window should just close automatically. Otherwise switching back/forth to the shell is quicker (with guard set up)

Still, nice package

**Comment by moxley** [comment] 2015-07-31 04:09
Duplicate of #7

**Closed by moxley** 2015-07-31 04:09 UTC
